
server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

# 다국어 설정을 위한 설정값을 yml에 설정값으로 추가
spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: passw0rd

management:
  endpoint:
    web:
      exposure:
        incldue: "*"